pipeline {
  agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jenkins-slave
    image: asia-south1-docker.pkg.dev/prj-shared-central-cicd36/repo-prj-shared-central-cicd36-uat-as1-01/jenkins-slave:v5
    env:
    securityContext:
      privileged: true
      runAsGroup: 0
      runAsUser: 0
  serviceAccountName: "jenkins-sa"
    
'''
            defaultContainer 'jenkins-slave'
        }
    }


 stages {

  stage('git checkout') {
   steps {
    git branch: 'main', credentialsId: 'gitlab-credentials', url: 'https://gitlab.nw18devops.com/news18-devops/news18-infra.git'
   }
  }

   stage('terraform init') {
       steps {
            dir('./prod/english/common/global-lb') {
                 sh "terraform init -no-color"
                      }
              }
      }
   stage('terraform validate') {
      steps {
         dir('./prod/english/common/global-lb') {
           sh "terraform validate -no-color"
                      }
                }
         }
  stage('terraform fmt') {
      steps {
         dir('./prod/english/common/global-lb') {
           sh "terraform fmt -no-color"
                      }
                }
         }

 stage('terraform plan') {
      steps {
         dir('./prod/english/common/global-lb') {
           sh "terraform plan -no-color"
                      }
                }
         }
 stage('Terraform Apply Approval') {
      steps {
        timeout(time: 5, unit: 'MINUTES'){
        input(message: 'Do you want to apply Terraform changes?', ok: 'Proceed')
       }
      }
    }

 stage('Terraform Apply') {
      when {
        expression {
            true
        }
    }
    steps {
        dir('./prod/english/common/global-lb') {
            sh "terraform apply -auto-approve -no-color"
        }
    }
}

 }}
 

